# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: TomcatDeployment@1
  inputs:
    TomcatUrl: 'http://azuronline.eastus.cloudapp.azure.com/'
    Username: 'deployer'
    Password: 'deployer'
    Warfile: '/home/vsts/work/1/s/target/mvnwebapp.war'
    Context: '/azure-deploy'
    ServerVersion: '7OrAbove'